/*!40101 SET NAMES utf8 */;
/*!40101 SET SQL_MODE=''*/;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

DROP TABLE IF EXISTS `wow_class_abilities`;
CREATE TABLE `wow_class_abilities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `class` int(11) NOT NULL,
  `title_de` text NOT NULL,
  `title_en` text NOT NULL,
  `title_es` text NOT NULL,
  `title_fr` text NOT NULL,
  `title_ru` text NOT NULL,
  `text_de` text NOT NULL,
  `text_en` text NOT NULL,
  `text_es` text NOT NULL,
  `text_fr` text NOT NULL,
  `text_ru` text NOT NULL,
  `icon` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=utf8 AUTO_INCREMENT=41;

INSERT INTO `wow_class_abilities` VALUES (1, 1, '', 'Defense', '', '', 'Защита', '', 'Mighty warriors depend on their heavy armor, shields, and battle prowess to defend themselves and ensure enemies don’t focus on their softer-skinned allies.', '', '', 'Могучие воины в бою полагаются на тяжелые доспехи, щиты и свои навыки. Их задача — не пропустить врага к менее защищенным членам отряда.', 'ability_defend.jpg');
INSERT INTO `wow_class_abilities` VALUES (2, 1, '', 'Melee damage', '', '', 'Ближний бой', '', 'Weapon mastery is a staple of warrior training, and they are capable of delivering high damage with enormous two-handed weapons or by wielding two weapons.', '', '', 'Мастерское владение оружием — самое главное для воина. Он может нанести противнику огромный урон, взяв тяжелое двуручное оружие или используя отдельное оружие в каждой руке.', 'ability_meleedamage.jpg');
INSERT INTO `wow_class_abilities` VALUES (3, 1, '', 'Rage', '', '', 'Гнев', '', 'As warriors deal or take damage, their rage grows, allowing them to deliver truly crushing attacks in the heat of battle.', '', '', 'Когда воин получает ранения, гнев его растет, позволяя в разгар битвы наносить поистине сокрушительные удары.', 'spell_nature_ancestralguardian.jpg');
INSERT INTO `wow_class_abilities` VALUES (4, 1, '', 'Stances', '', '', 'Стойки', '', 'By changing their stance during battle, warriors can adjust their focus in combat, dealing greater damage, defending more carefully against enemy attacks, or striking a balance between the two.', '', '', 'Изменив стойку во время боя, воин может подстроиться к ситуации: нанося больший урон, лучше парируя вражеские удары или придерживаясь золотой середины.', 'ability_warrior_offensivestance.jpg');
INSERT INTO `wow_class_abilities` VALUES (5, 2, '', 'Defense', '', '', 'Защита', '', 'Stalwart paladins are trained to use the heaviest armor and shields, and can utilize their skill to ensure that enemies focus on them, defending weaker members of their group.', '', '', 'Паладины используют самые тяжелые доспехи и щиты, отвлекая на себя противника и защищая более слабых членов отряда.', 'spell_holy_avengersshield.jpg');
INSERT INTO `wow_class_abilities` VALUES (6, 2, '', 'Melee damage', '', '', 'Ближний бой', '', 'Paladins charge their weapons with holy might, allowing them to deal additional damage with their strikes.', '', '', 'Паладины наделяют свое оружие священной силой, которая позволяет наносить врагу огромный урон.', 'spell_holy_crusaderstrike.jpg');
INSERT INTO `wow_class_abilities` VALUES (7, 2, '', 'Auras, Blessings, and Seals', '', '', 'Ауры, благословения и печати', '', 'As champions of order, paladins are extremely potent in a group – their auras, blessings and seals can improve damage and survivability for both themselves and their party.', '', '', 'Будучи защитниками порядка, паладины отлично работают в команде. Их ауры, благословения и печати могут как защищать команду, так и делать ее более опасной для противника.', 'spell_holy_devotionaura.jpg');
INSERT INTO `wow_class_abilities` VALUES (8, 2, '', 'Healing', '', '', 'Лечение', '', 'Paladins’ potent healing abilities can ensure that they and their allies remain in fighting shape.', '', '', 'Когда кто-то в команде ранен, паладин может использовать навыки целителя.', 'spell_holy_layonhands.jpg');
INSERT INTO `wow_class_abilities` VALUES (9, 3, '', 'Pets', '', '', 'Питомцы', '', 'Hunters tame the beasts of the wild, and those beasts serve in return by assaulting their enemies and shielding them from harm.', '', '', 'Охотники приручают диких зверей, которые служат им, нападая на врагов и прикрывая своим телом хозяина.', 'ability_hunter_beasttaming.jpg');
INSERT INTO `wow_class_abilities` VALUES (10, 3, '', 'Ranged damage', '', '', 'Бой на расстоянии', '', 'Whether wielding bows, guns, or crossbows, hunters are deadly with ranged weapons. They are capable of dishing out consistently high damage.', '', '', 'Владея луком, ружьем или арбалетом, охотник становится смертельно опасен. Он может нанести противнику колоссальный урон на расстоянии.', 'inv_weapon_bow_02.jpg');
INSERT INTO `wow_class_abilities` VALUES (11, 3, '', 'Traps', '', '', 'Ловушки', '', 'Hunters are consummate survivalists, able to set traps to burn, freeze, and disable potential prey.', '', '', 'Охотники являются специалистами по выживанию и могут устанавливать ловушки, замораживающие, сжигающие или останавливающие добычу.', 'spell_frost_chainsofice.jpg');
INSERT INTO `wow_class_abilities` VALUES (12, 3, '', 'Soloing', '', '', 'Одиночка', '', 'Thanks to their pets and damage output, hunters are effective at completing quests and leveling quickly, even when they’re alone.', '', '', 'Благодаря питомцам и большому наносимому урону охотники могут успешно выполнять задания и повышать свой уровень, действуя в одиночку.', 'ability_upgrademoonglaive.jpg');
INSERT INTO `wow_class_abilities` VALUES (13, 4, '', 'Stealth', '', '', 'Незаметность', '', 'Rogues sneak about the battlefield, hiding from enemies and delivering surprise attacks to the unwary when opportunity arises.', '', '', 'Скрываясь от противника, разбойники крадутся по краю поля боя и наносят неожиданные удары.', 'ability_stealth.jpg');
INSERT INTO `wow_class_abilities` VALUES (14, 4, '', 'Melee damage', '', '', 'Ближний бой', '', 'By coating their dual-wielded blades with deadly poisons, rogues can deliver catastrophic damage to their targets.', '', '', 'Нанеся на оружие яд, разбойник может нанести врагу огромный урон.', 'inv_weapon_shortblade_15.jpg');
INSERT INTO `wow_class_abilities` VALUES (15, 4, '', 'Evasion', '', '', 'Ускользание', '', 'When endangered, rogues have many tools at their disposal to avoid their enemies’ gaze and, if necessary, their attacks.', '', '', 'Почувствовав опасность, разбойник использует целый арсенал инструментов, чтобы скрыться от взгляда и, если это необходимо, избежать атаки противника.', 'spell_shadow_shadowward.jpg');
INSERT INTO `wow_class_abilities` VALUES (16, 4, '', 'Combos', '', '', 'Приемы', '', 'By planning and combining successive melee attacks, rogues can build up combo points that allow them to deliver devastating finishing blows in combat.', '', '', 'Разбойники могут выстраивать связки ударов, позволяющие выполнить сокрушительный добивающий прием.', 'ability_rogue_eviscerate.jpg');
INSERT INTO `wow_class_abilities` VALUES (17, 5, '', 'Healing', '', '', 'Лечение', '', 'Priests utilize their holy powers to restore their health and that of their comrades.', '', '', 'Жрецы пользуются доступом к священным силам, чтобы восстанавливать свое здоровье и здоровье союзников.', 'spell_holy_greaterheal.jpg');
INSERT INTO `wow_class_abilities` VALUES (18, 5, '', 'Ranged damage', '', '', 'Бой на расстоянии', '', 'Priestly Shadow magic can deliver great amounts of immediate damage, or wracking pains that punish foes over longer periods of time.', '', '', 'Использование темной магии позволяет жрецам мгновенно наносить огромный урон врагу или растягивать причиняемую боль.', 'spell_shadow_shadowform.jpg');
INSERT INTO `wow_class_abilities` VALUES (19, 5, '', 'Power words', '', '', 'Слова силы', '', 'By calling on mystic shielding and holy empowerment, priests can prevent incoming damage and improve their defenses and those of their allies.', '', '', 'Создавая магические щиты и взывая к великим силам, жрецы могут отводить вред от себя и своих спутников.', 'spell_holy_powerwordshield.jpg');
INSERT INTO `wow_class_abilities` VALUES (20, 5, '', 'Mind Control', '', '', 'Контроль над разумом', '', 'Priests’ connection with the minds and spirits of living beings allows them to control and manipulate others.', '', '', 'Устанавливая связь с разумом живых существ, жрецы подчиняют их своей воле, используя тела и умения жертв.', 'spell_shadow_shadowworddominate.jpg');
INSERT INTO `wow_class_abilities` VALUES (21, 6, '', 'Defense', '', '', 'Защита', '', 'To protect themselves and their fellows from death in battle, death knights gird themselves in heavy armor and parry attacks with their blades.', '', '', 'Чтобы защитить себя и своих союзников в бою, рыцари смерти облачаются в тяжелые доспехи и стараются парировать вражеские атаки мечом.', 'spell_nature_shamanrage.jpg');
INSERT INTO `wow_class_abilities` VALUES (22, 6, '', 'Melee damage', '', '', 'Ближний бой', '', 'Death knight runeblades are empowered with dark magic; they can expend the power of their runes for vicious attacks.', '', '', 'Рунические клинки рыцарей смерти излучают темную магию; в бою руны придают силу их ударам.', 'spell_deathknight_empowerruneblade.jpg');
INSERT INTO `wow_class_abilities` VALUES (23, 6, '', 'Utility', '', '', 'Разнообразие', '', 'As former champions of the Lich King, death knights can command the dead as minions, freeze their foes with ice, and inflict weakening diseases.', '', '', 'Будучи бывшими защитниками Короля-лича, рыцари смерти могут командовать мертвыми, поражать врага магией льда и ослаблять его болезнями.', 'spell_shadow_raisedead.jpg');
INSERT INTO `wow_class_abilities` VALUES (24, 6, '', 'Runeforging', '', '', 'Ковка рун', '', 'Death knights have a personal connection with their blades, and can forge runes into them in order to increase their power.', '', '', 'Рыцари смерти связаны со своими клинками и могут высекать на них руны, увеличивая силу оружия.', 'spell_deathknight_frozenruneweapon.jpg');
INSERT INTO `wow_class_abilities` VALUES (25, 7, '', 'Healing', '', '', 'Лечение', '', 'By calling on their spiritual power, shaman can restore health to injured allies.', '', '', 'При помощи внутренней духовной силы шаман может исцелять раненых друзей.', 'spell_nature_healingwavegreater.jpg');
INSERT INTO `wow_class_abilities` VALUES (26, 7, '', 'Melee damage', '', '', 'Ближний бой', '', 'Shaman enhance their weapons with elemental effects, empowering their blows with the power of fire, wind, or ice.', '', '', 'Шаманы придают своему оружию свойства стихий, заставляя его жечь, морозить или иным образом ранить врага.', 'spell_shaman_unleashweapon_wind.jpg');
INSERT INTO `wow_class_abilities` VALUES (27, 7, '', 'Ranged damage', '', '', 'Бой на расстоянии', '', 'Shaman can choose to deploy a wide array of different totems, each providing allies with a unique effect, including improved restoration, greater damage, faster attacks, and more.', '', '', 'Шаман может использовать силы стихий, чтобы на расстоянии поразить противника молнией, подземным толчком или извержением лавы.', 'spell_nature_lightning.jpg');
INSERT INTO `wow_class_abilities` VALUES (28, 7, '', 'Totems', '', '', 'Тотемы', '', 'Shaman can choose to deploy a wide array of different totems, each providing allies with a unique effect, including improved restoration, greater damage, faster attacks, and more.', '', '', 'Тотемы шамана обладают массой положительных свойств: они увеличивают скорость атаки, эффективность восстановления и наносимый противнику урон.', 'spell_shaman_dropall_02.jpg');
INSERT INTO `wow_class_abilities` VALUES (29, 8, '', 'Ranged damage', '', '', 'Бой на расстоянии', '', 'Mages can expend mana in order to deal high amounts of damage with amazing speed, though they must be wary of exhausting themselves.', '', '', 'Маги могут расходовать ману, очень быстро нанося противнику огромный урон, но они должны быть осторожны, чтобы не истощить самих себя.', 'spell_fire_flamebolt.jpg');
INSERT INTO `wow_class_abilities` VALUES (30, 8, '', 'Area of effect spells', '', '', 'Заклинания, действующие на область', '', 'By calling upon sheets of ice, columns of flame, and waves of arcane power, mages can effectively attack multiple foes at the same time.', '', '', 'Создавая глыбы льда, столбы пламени и шквалы тайной магии, маги могут одновременно поражать нескольких врагов.', 'spell_frost_icestorm.jpg');
INSERT INTO `wow_class_abilities` VALUES (31, 8, '', 'Control', '', '', 'Контроль', '', 'A mage has many options for controlling the battlefield, from freezing enemies in place to transforming them into helpless critters.', '', '', 'Маг, заставший противника врасплох на поле боя, может действовать по-разному — скажем, заморозить его заживо или превратить в безвредное животное.', 'spell_nature_polymorph.jpg');
INSERT INTO `wow_class_abilities` VALUES (32, 8, '', 'Teleportation', '', '', 'Телепортация', '', 'Mages possess the ability to transport themselves and their allies between cities and can summon replenishing food and water.', '', '', 'Маги обладают способностью перемещаться между городами и создавать пищу и воду, где бы они ни находились.', 'spell_arcane_portaldalaran.jpg');
INSERT INTO `wow_class_abilities` VALUES (33, 9, '', 'Pets', '', '', 'Питомцы', '', 'Warlocks bind demons to their will; these infernal denizens defend their masters with their lives or rain death upon their enemies.', '', '', 'Чернокнижники подчиняют своей воле демонов: обитатели преисподней защищают своих хозяев и сражаются с их врагами.', 'spell_shadow_summonfelhunter.jpg');
INSERT INTO `wow_class_abilities` VALUES (34, 9, '', 'Curses and Drains', '', '', 'Проклятья и похищения', '', 'Warlocks are able to curse their foes: slowing them, crippling their combat effectiveness, and weakening their resistance. They can also drain enemies’ health or mana to rejuvenate themselves.', '', '', 'Чернокнижники умеют проклинать своих врагов, замедляя их, снижая силу их ударов и ослабляя защиту. Также они могут красть здоровье и ману противника, пополняя свои запасы.', 'spell_shadow_lifedrain02.jpg');
INSERT INTO `wow_class_abilities` VALUES (35, 9, '', 'Ranged Damage', '', '', 'Бой на расстоянии', '', 'Warlocks deliver fire and shadow damage with their spells, and they’re able to hurt others both instantly and with ongoing afflictions.', '', '', 'Заклинания чернокнижников обрушивают на врагов огонь и тьму. Они могут наносить как мгновенный, так и отложенный урон.', 'spell_shadow_shadowbolt.jpg');
INSERT INTO `wow_class_abilities` VALUES (36, 9, '', 'Soul Shards', '', '', 'Осколки души', '', 'Warlocks can drain enemy souls and use them to empower their own spells, making them swifter or more deadly.', '', '', 'Чернокнижники крадут душу соперника и используют ее для придания силы своим заклинаниям, делая их быстрее и смертоноснее.', 'inv_misc_gem_amethyst_02.jpg');
INSERT INTO `wow_class_abilities` VALUES (37, 11, '', 'Versatility', '', '', 'Изменчивость', '', 'Druids’ changing forms let them assume different roles and focus on either tanking, healing, or damage. They can also shapeshift to travel faster on land, sea, and air.', '', '', 'Cпособность друидов менять обличье позволяет им играть разные роли в команде: &quot;танка&quot;, целителя или бойца. Также смена облика дает возможность быстро передвигаться по суше, морю и воздуху.', 'ability_druid_mastershapeshifter.jpg');
INSERT INTO `wow_class_abilities` VALUES (38, 11, '', 'Healing', '', '', 'Лечение', '', 'By calling upon the powers of nature, druids are able to swiftly restore health to their injured allies.', '', '', 'C помощью сил природы друиды могут быстро восстановить здоровье раненых товарищей.', 'spell_nature_resistnature.jpg');
INSERT INTO `wow_class_abilities` VALUES (39, 11, '', 'Defense', '', '', 'Защита', '', 'When shapeshifted into their bear form, druids possess a thick skin and imposing presence that makes them ideal front-line protectors of weaker party members.', '', '', 'Приняв обличье медведя, друид получает толстую шкуру и грозный вид. Так он может лучше защищать слабых членов команды, сражаясь в первых рядах.', 'ability_druid_demoralizingroar.jpg');
INSERT INTO `wow_class_abilities` VALUES (40, 11, '', 'Melee and ranged damage', '', '', 'Рукопашная и бой на расстоянии', '', 'Druids can take on the form of a savage cat in order to claw and bite their enemies up close, or that of a wild moonkin to blast enemies from afar.', '', '', 'Друиды могут принимать вид диких кошек, чтобы кусать врагов и рвать их когтями, либо превращаться в лунных совухов, чтобы разить противника на расстоянии.', 'inv_misc_monsterclaw_03.jpg');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;